name: Release

on:
  push:
    branches:
      - main
      - 'test-*'
      - 'beta'
      - 'next'
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: |
          rm -rf out
          npm run generate
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
